import { ReactNode } from 'react';

import { dir } from 'i18next';
import type { Metadata } from 'next';

import '@/styles/globals.css';

import { Providers } from '@/app/[locale]/providers';

export const metadata: Metadata =
{
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children, params: { locale } }: { children: ReactNode, params: { locale: string } })
{
    return (
        <html lang={ locale }>
            <body dir={ dir(locale) }>
                <Providers>
                    { children }
                </Providers>
            </body>
        </html>
    );
}
